<?xml version="1.0"?>
<robot name ="husky_ugv" xmlns:xacro="https://www.ros.org/wiki/xacro">

    <xacro:property name="chassis_length" value="0.85"/>
    <xacro:property name="chassis_width" value="0.420"/>
    <xacro:property name="chassis_height" value="0.242"/>
    <xacro:property name="chassis_mass" value="50.0"/>
    <xacro:property name="wheel_radius" value="0.160"/>
    <xacro:property name="wheel_thickness" value="0.139"/>
    <xacro:property name="wheel_separation" value="0.60"/>
    <xacro:property name="wheel_mass" value="2.0"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
    
    
    <!-- Base Footprint-->

    <link name="base_footprint"/>

    <!-- Base Link-->

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                     iyy="0.1" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${chassis_height/2 + wheel_radius}" rpy="0 0 0"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>


    <!-- Front Left Wheel -->

    <link name="front_left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                     iyy="0.1" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="front_left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="front_left_wheel_joint" type="continuous">
        <origin xyz="0.220 ${chassis_width/2 + wheel_thickness/2 + 0.02} -${chassis_height/2}" rpy="-1.57 0 0"/>
        <parent link="base_link"/>
        <child link="front_left_wheel"/>
        <axis xyz="0 0 1" rpy="0 0 0"/>
    </joint>


    <!-- Front Right Wheel -->
    
    <link name="front_right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                     iyy="0.1" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="front_right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="front_right_wheel_joint" type="continuous">
        <origin xyz="0.220 -${chassis_width/2 + wheel_thickness/2 + 0.02} -${chassis_height/2}" rpy="1.57 0 0"/>
        <parent link="base_link"/>
        <child link="front_right_wheel"/>
        <axis xyz="0 0 -1" rpy="0 0 0"/>
    </joint>

    <!-- Rear Left Wheel -->
    
    <link name="rear_left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                     iyy="0.1" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="rear_left_wheel_joint" type="continuous">
        <origin xyz="-0.220 ${chassis_width/2 + wheel_thickness/2 + 0.02} -${chassis_height/2}" rpy="-1.57 0 0"/>
        <parent link="base_link"/>
        <child link="rear_left_wheel"/>
        <axis xyz="0 0 1" rpy="0 0 0"/>
    </joint>

    <!-- Rear Right Wheel -->
    
    <link name="rear_right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                     iyy="0.1" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="rear_right_wheel_joint" type="continuous">
        <origin xyz="-0.220 -${chassis_width/2 + wheel_thickness/2 + 0.02} -${chassis_height/2}" rpy="1.57 0 0"/>
        <parent link="base_link"/>
        <child link="rear_right_wheel"/>
        <axis xyz="0 0 -1" rpy="0 0 0"/>
    </joint>

    <!-- Velodyne Mount -->

    <link name="velodyne_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.010" length="0.30"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.010" length="0.30"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                     iyy="0.01" iyz="0.0"
                     izz="0.01"/>
        </inertial>
    </link>

    <gazebo reference="velodyne_mount">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="velodyne_mount_joint" type="fixed">
        <origin xyz="0 0 ${chassis_height/2 + 0.15}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="velodyne_mount"/>
    </joint>    

    <!-- Velodyne -->

    <link name="velodyne">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.05"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.05"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.05" ixy="0.0" ixz="0.0"
                     iyy="0.05" iyz="0.0"
                     izz="0.05"/>
        </inertial>
    </link>

    <gazebo reference="velodyne">
        <material>Gazebo/Red</material>
    </gazebo>

    <joint name="velodyne_joint" type="fixed">
        <origin xyz="0 0 0.15" rpy="0 0 0"/>
        <parent link="velodyne_mount"/>
        <child link="velodyne"/>
    </joint>

    <!-- camera Mount -->

    <link name="camera_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.005" length="0.10"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.005" length="0.10"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                     iyy="0.01" iyz="0.0"
                     izz="0.01"/>
        </inertial>
    </link>

    <gazebo reference="camera_mount">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="camera_mount_joint" type="fixed">
        <origin xyz="${chassis_length/2 - 0.05} 0 ${chassis_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="camera_mount"/>
    </joint>

    <!-- Camera -->

    <link name="camera">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.10 0.02"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.10 0.02"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.05" ixy="0.0" ixz="0.0"
                     iyy="0.05" iyz="0.0"
                     izz="0.05"/>
        </inertial>
    </link>

    <gazebo reference="camera">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="camera_joint" type="fixed">
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <parent link="camera_mount"/>
        <child link="camera"/>
    </joint>

    <!-- ROS2 Control Plugin -->

    <gazebo>
        <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
            <ros>
                <!-- <namespace>/</namespace> -->
            </ros>
            <update_rate>100</update_rate>

            <left_joint>rear_left_wheel_joint</left_joint>
            <right_joint>rear_right_wheel_joint</right_joint>

            <wheel_separation>${wheel_separation}</wheel_separation>
            <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

            <command_topic>cmd_vel</command_topic>
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>

            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
            <update_rate>50</update_rate>
            <joint_name>front_left_wheel_joint</joint_name>
            <joint_name>front_right_wheel_joint</joint_name>
            <joint_name>rear_left_wheel_joint</joint_name>
            <joint_name>rear_right_wheel_joint</joint_name>
        </plugin>
    </gazebo>

</robot>