<?xml version="1.0"?>
<robot name ="custom_husky" xmlns:xacro="https://www.ros.org/wiki/xacro">

    <xacro:include filename="ros2_control.xacro"/>

    <xacro:property name="chassis_length" value="0.85"/>
    <xacro:property name="chassis_width" value="0.420"/>
    <xacro:property name="chassis_height" value="0.242"/>
    <xacro:property name="chassis_mass" value="50.0"/>
    <xacro:property name="wheel_radius" value="0.160"/>
    <xacro:property name="wheel_thickness" value="0.139"/>
    <xacro:property name="wheel_mass" value="2.0"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
    
    
    <!-- Base Footprint-->

    <link name="base_footprint"/>

    <!-- Base Link-->

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                     iyy="0.1" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${chassis_height/2 + wheel_radius}" rpy="0 0 0"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>

    <!-- Front Left Wheel -->

    <link name="front_left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                     iyy="0.1" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="front_left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="front_left_wheel_joint" type="continuous">
        <origin xyz="0.220 ${chassis_width/2 + wheel_thickness/2 + 0.02} -${chassis_height/2}" rpy="-1.57 0 0"/>
        <parent link="base_link"/>
        <child link="front_left_wheel"/>
        <axis xyz="0 0 1" rpy="0 0 0"/>
    </joint>

    <!-- Front Right Wheel -->
    
    <link name="front_right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                     iyy="0.1" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="front_right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="front_right_wheel_joint" type="continuous">
        <origin xyz="0.220 -${chassis_width/2 + wheel_thickness/2 + 0.02} -${chassis_height/2}" rpy="1.57 0 0"/>
        <parent link="base_link"/>
        <child link="front_right_wheel"/>
        <axis xyz="0 0 -1" rpy="0 0 0"/>
    </joint>

    <!-- Rear Left Wheel -->
    
    <link name="rear_left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                     iyy="0.1" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="rear_left_wheel_joint" type="continuous">
        <origin xyz="-0.220 ${chassis_width/2 + wheel_thickness/2 + 0.02} -${chassis_height/2}" rpy="-1.57 0 0"/>
        <parent link="base_link"/>
        <child link="rear_left_wheel"/>
        <axis xyz="0 0 1" rpy="0 0 0"/>
    </joint>

    <!-- Rear Right Wheel -->
    
    <link name="rear_right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                     iyy="0.1" iyz="0.0"
                     izz="0.1"/>
        </inertial>
    </link>

    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="rear_right_wheel_joint" type="continuous">
        <origin xyz="-0.220 -${chassis_width/2 + wheel_thickness/2 + 0.02} -${chassis_height/2}" rpy="1.57 0 0"/>
        <parent link="base_link"/>
        <child link="rear_right_wheel"/>
        <axis xyz="0 0 -1" rpy="0 0 0"/>
    </joint>

    <!-- Velodyne Mount -->

    <link name="velodyne_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.010" length="0.30"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.010" length="0.30"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                     iyy="0.01" iyz="0.0"
                     izz="0.01"/>
        </inertial>
    </link>

    <gazebo reference="velodyne_mount">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="velodyne_mount_joint" type="fixed">
        <origin xyz="0 0 ${chassis_height/2 + 0.15}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="velodyne_mount"/>
    </joint>    

    <!-- Velodyne -->

    <link name="velodyne">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.05"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.05"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.05" ixy="0.0" ixz="0.0"
                     iyy="0.05" iyz="0.0"
                     izz="0.05"/>
        </inertial>
    </link>

    <gazebo reference="velodyne">
        <material>Gazebo/Red</material>
        <sensor type="gpu_ray" name="velodyne_lidar">
            <pose>0 0 0 0 0 0</pose>
            <visualize>false</visualize>
<<<<<<< HEAD
            <update_rate>20</update_rate>
=======
            <update_rate>30</update_rate>
>>>>>>> 21d0bad (add nav2)
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>16</samples>
                        <resolution>1</resolution>
                        <min_angle>-0.261799</min_angle>
                        <max_angle>0.261799</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.2</min>
                    <max>100.0</max>
                    <resolution>0.01</resolution>   
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_velodyne_controller" filename="libgazebo_ros_velodyne_laser.so">
            <ros>
                <remapping>~/out:=/velodyne_points</remapping>
            </ros>
            <frame_name>velodyne</frame_name>
            </plugin>
        </sensor>

    </gazebo>

    <joint name="velodyne_joint" type="fixed">
        <origin xyz="0 0 0.15" rpy="0 0 0"/>
        <parent link="velodyne_mount"/>
        <child link="velodyne"/>
    </joint>

    <!-- Camera Mount -->

    <link name="camera_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.005" length="0.10"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.005" length="0.10"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                     iyy="0.01" iyz="0.0"
                     izz="0.01"/>
        </inertial>
    </link>

    <gazebo reference="camera_mount">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="camera_mount_joint" type="fixed">
        <origin xyz="${chassis_length/2 - 0.05} 0 ${chassis_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="camera_mount"/>
    </joint>

    <!-- Camera Optical Link -->

    <link name="camera_optical_link"/>

    <joint name="camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${pi/2} 0 -${pi/2}"/>
        <parent link="camera"/>
        <child link="camera_optical_link"/>
    </joint>

    <!-- Camera -->

    <link name="camera">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.10 0.02"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.10 0.02"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.05" ixy="0.0" ixz="0.0"
                     iyy="0.05" iyz="0.0"
                     izz="0.05"/>
        </inertial>
    </link>

    <gazebo reference="camera">
        <material>Gazebo/Orange</material>
        <sensor name="depth_camera" type="depth">
            <always_on>true</always_on>
            <visualize>true</visualize>
<<<<<<< HEAD
            <update_rate>30</update_rate>
=======
            <update_rate>15</update_rate>
>>>>>>> 21d0bad (add nav2)
            <pose>0 0 0 0 0 0</pose>
            <depth_camera name="depth_cam">
                <horizontal_fov>2</horizontal_fov>
                <image>
                    <width>320</width>
                    <height>240</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>10.0</far>
                </clip>
            </depth_camera>
            <plugin name="depth_camera_driver" filename="libgazebo_ros_camera.so">
                <frame_name>camera_optical_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

    <joint name="camera_joint" type="fixed">
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <parent link="camera_mount"/>
        <child link="camera"/>
    </joint>

    <!-- IMU Link -->

    <link name="imu_link"/>

    <joint name="imu_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

    <gazebo reference="imu_link">
        <sensor type="imu" name="imu_sensor">
        <always_on>true</always_on>
        <update_rate>50</update_rate>
        <visualize>true</visualize>
        <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
            <ros>
                <namespace>/</namespace>
                <remapping>imu_plugin/out:=imu/data</remapping>
            </ros>
        <body_name>imu_link</body_name>
        <frame_name>imu_link</frame_name>
        <gaussian_noise>0.01</gaussian_noise>
        </plugin>
        </sensor>
    </gazebo>

</robot>
